# Generated by Django 4.0 on 2022-01-29 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('rollno', models.IntegerField()),
                ('email', models.CharField(max_length=15)),
                ('mobile', models.IntegerField()),
                ('address', models.CharField(max_length=300)),
                ('sub1', models.IntegerField()),
                ('sub2', models.IntegerField()),
                ('sub3', models.IntegerField()),
            ],
            options={
                'db_table': 'MyApp',
            },
        ),
    ]
